chore: remove codepush dep (#11526)
* feat: Support ☯️ (#11417)

* feat: add dark mode [part 1]

* chore: add dark mode onboarding for artsy employees

* chore: city guide fixes

* chore: fix: feature onboarding

* fix: more broken dark mode instances

* chore(deps): update dep @artsy/palette-mobile from 14.0.24 to v14.0.28 (#11543)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* chore: update metaphysics graphql schema (#11558)

* chore: update metaphysics graphql schema (#11559)

* chore: update metaphysics graphql schema (#11560)

* chore: update metaphysics graphql schema (#11561)

* chore: update metaphysics graphql schema (#11562)

* chore: update metaphysics graphql schema (#11563)

* chore: update metaphysics graphql schema (#11564)

* fix(EMI-2224): Refactor Register to Bid flow (#11522)

* fix(EMI-2224): Refactor Register to Bid flow

* refactor confirm bid screen

* refactor bid results screen

* improve credit card screen performance

* add BidFlowContextStore

* refactor Price Summary

* fix confirmBid tests

* fix BidResult tests

* refactor bidding navigation

* fix issue with Select options not rendering

* refactor and fix select max bid tests

* fix credit card form tests

* fix phone number form tests

* fix registration result tests

* refactor bid flow tests

* fix payment info tests

* fix registration tests

* fix bid result tests

* update confirm bid tests

* move BiddingNavigator to Navigation

* remove else in backHandler

* add Sentry capturing for errors in the bid flow

* replace captureException to captureMessage

* fix keyboard avoiding view for Android

* promisify useCreateCreditCard hook

* add sentry mocks in ConfirmBid tests

* chore(deps): update dep @artsy/cohesion from 4.234.0 to v4.235.0 (#11565)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* fix: margins on browseSimilarScreen (#11567)

* fix: android dev menu navigateTo input (#11568)

* fix(ONYX-1516): fix null in auction result screen header, and spacing on the auctions screen (#11510)

* fixL fix auction result header, and spacing

* chore: address review comments

* feat(InfiniteDiscovery): bottomSheet backdrop, bottomeSheet handle and geolocation (#11551)

* fix: adjust bottom sheet text height

* feat: organizes bottom sheet elements/hooks and allows closing the bottomsheet when the backdrop is visible

* feat: remove geolocation usage in the bottom sheet

* fix(EMI-2279): Attempt to improve HomeView Tasks performance (#11569)

* fix(EMI-2279): Attempt to improve HomeView Tasks performance

* fix typing issues

* remove unused asyncs

* fix(PBRW-487): Fix double artwork navigation issues (#11571)

* chore(deps): update dep @artsy/cohesion from 4.235.0 to v4.236.0 (#11572)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* chore: fix yarn:doctor script (#11573)

Was unintentionally erroring out when determining the installed XCode version
and the versions mismatch.

**Expected**

```
🟡 Xcode is installed but the version is incorrect. Installed: 16.2, Expected: 16.1
```

**Actual**

```
ReferenceError: desiredVersion is not defined
    at checkXcodeVersion (/Users/devon/code/artsy/eigen/scripts/utils/doctor.js:244:103)
    at main (/Users/devon/code/artsy/eigen/scripts/utils/doctor.js:287:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
🔴 Xcode is not installed or there was an error determining the version.
```

* chore(build): support user installations of asdf at ~/$HOME/.asdf (#11574)

I'm currently running v0.14.1 of asdf. The installation guide at the time
supported a user-scoped installation at `~/$HOME/.asdf`.

This commit adds a branch accounting for that installation path in our Build >
pre-actions script within the Artsy XCode scheme.

```bash
elif [ -f "$HOME/.asdf/bin/asdf" ]; then
  ASDF_DIR="${ASDF_DIR:-$HOME/.asdf}"
  export PATH="$ASDF_DIR/bin:$ASDF_DIR/shims:$PATH"
  asdf local nodejs $NODE_VERSION
```

* feat(dia-1025): infinite discovery tracking (#11570)

* fix: text color on onboarding welcome screen in dark mode (#11575)

fix: auth flow dark mode issues

* fix: wrong key for braze prod (#11576)

fix wrong key for braze prod

* chore(deps): update dep @artsy/palette-mobile from 14.0.28 to v14.0.29 (#11577)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* chore: update metaphysics graphql schema (#11578)

* fix: dark mode issues on infinite discovery (#11579)

fix: dark mode issues on infinite discovert

* chore(deps): update dep @artsy/cohesion from 4.236.0 to v4.237.0 (#11582)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* chore: Remove old code from BidFlow refactor (#11566)

* chore: Remove old code from BidFlow refactor

* bring back tracking

* chore: update metaphysics graphql schema (#11583)

* feat(ONYX-509): create shows for you screen (#11555)

* feat: add shows for you screen [draft]

* fix: fix refetchable query name

* feat: adjust showCard component to be rendered on the list view

* chore: display in two collumns on big screens

* chore: refactor, write tests

* chore: refactor ad reuse card component for articles

* chore: adjust types

* feat: navigate from header and track

* chore: update metaphysics graphql schema (#11586)

* chore: remove codepush dep

* chore: remove appcenter and fix broken android build

---------

Co-authored-by: Mounir Dhahri <soussouheros@gmail.com>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Artsy <artsyit@users.noreply.github.com>
Co-authored-by: Sultan Al-Maari <sltun2oo9@gmail.com>
Co-authored-by: Daria Kozlova <daria.kozlova@artsymail.com>
Co-authored-by: Carlos <araujobarret@gmail.com>
Co-authored-by: devon blandin <dblandin@gmail.com>
Co-authored-by: Nikita Skalkin <nikskalkin@gmail.com>
Co-authored-by: Brian Beckerle <49686530+brainbicycle@users.noreply.github.com>